<html>
    <head>
        <meta charset="utf-8"/>
        <title>Home</title>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <?php foreach($posts as $item) : ?>
			<div><a href="/post/<?= str_replace('.md','',$item) ?>"><?= $item ?></a></div>
		<?php endforeach; ?>
    </body>
</html>
